### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DevMinkh** [Xogy/xsound#1]
is it possible for a nightclub extension to use more then one location with just one song YT or MP3

LG Minkh

**Comment by Xogy** [comment]
Well, this question is tricky.. you can choose two location to play same song but one of them will have delay (like 0.3s if it loads fast) and if they're too close together you will hear them both and it will not sound good... My system isnt really ready for multiple positions for single song, it is possible do it but would required heavy change to code... maybe i will do it in my next sound system i am planning to do, but i cannot give any date cause i got lot work to do on other projects and real life is also thing. Hope i helped somehow.

However this sound system support

direct url
youtube link
stream radio
youtube stream
