### ISSUE TITLE
Asking for Interact-sound compatibility clarifications & making an offer

### ISSUE THREAD

**Issue by benitoll** [Xogy/xsound#10]
I'm sorry to make questions that I myself could find the answer to, but I think you already have the answers, I'm overloaded with work and at the same time I'm making an offer

- Should `interact-sound` NOT be used alongside `Xsound`?

- By `Can work with API interact sound` in `README.MD`, did you mean it's fully compatible BUT one has to change the triggered events or make a compatibility layer, right?

- if made a Plug & Play compatibility layer (with `interact-sound`'s event names) and made a pull request, would you accept it?

**Comment by Xogy** [comment]
1. interact-sound can be used alongside xsound, it is disabled by default in config so nothing will happen.
2. if your server use some kind of custom events for better "Security" for interact sound then yes, you will have to change them.
3. if those changes will be unnecessary like the guy with crewPhone did example here: https://github.com/Xogy/xsound/blob/master/addon/crewphone/client/client.lua I will most likely not accept anything.
