### ISSUE TITLE
Uncontrollable after changing radio station links

### ISSUE THREAD

**Issue by PERPGamer** [Xogy/xsound#11]
Sometimes after changing radio stations (like ones from here: https://github.com/ozok/OooPlayer/blob/master/Release/Win32/Radios/All.txt ), the music stops being controllable when it was before. This leads to the music getting stuck on/volume. For example, I was playing a top 40 channel (volume/play/stop works), changed to a country channel  (volume/play/stop works), and then back to the same top 40 channel where the volume/play/stop doesn't work. The only way I can get the music to stop is by restarting xsound. When they become uncontrollable it can lead to the music being heard on players not nearby which they cannot stop hearing the music until the restart of xsound. 
Along with being unable to change the radio from the current link can happen, making it get stuck off until you mess with the volume/play/pause buttons.
(Using MusicEverywhere)

**Comment by Xogy** [comment]
> Sometimes after changing radio stations (like ones from here: https://github.com/ozok/OooPlayer/blob/master/Release/Win32/Radios/All.txt ), the music stops being controllable when it was before. This leads to the music getting stuck on/volume. For example, I was playing a top 40 channel (volume/play/stop works), changed to a country channel (volume/play/stop works), and then back to the same top 40 channel where the volume/play/stop doesn't work. The only way I can get the music to stop is by restarting xsound. When they become uncontrollable it can lead to the music being heard on players not nearby which they cannot stop hearing the music until the restart of xsound.
> Along with being unable to change the radio from the current link can happen, making it get stuck off until you mess with the volume/play/pause buttons.
> (Using MusicEverywhere)

It doesn't have to be an exactly the issue with xsound, something in "MusicEveryWhere" can cause this problem, but I will try to look into it.. can you describe your movement to get the volume stuck? For example, you get it stuck by first playing youtube, then mp3 and after that, you will play some radio.

**Comment by PERPGamer** [comment]
> It doesn't have to be exactly the issue with xsound, something in "MusicEveryWhere" can cause this problem, but I will try to look into it.. can you describe your movement to get the volume stuck? For example, you get it stuck by first playing youtube, then mp3 and after that, you will play some radio.
> 
> or would be best to send me the exact same thing you did, all URLs that lead volume get stuck.

Sorry for the late reply but I seem to, sadly, be unable to replicate the problem consistently (the uncontrollable part) though getting stuck off is very easy to replicate. By playing: http://173.244.215.163:8270/ (GotRadio Top 40 station) and then going to like http://173.244.215.163:8250/ (GotRadio The Mix station) it will not start to play without messing with the volume/play/pause buttons or putting the link in a few times. The getting stuck on only seems to happen randomly with other players on, I'm thinking the get stuck on one might be from _MusicEverywhere_ or just. At any rate, I have reported it to the creator of that addon as well since the more I think about it, it could be either-or (as _MusicEverywhere_ plays on the entity and if it does get glitched, it stops once the vehicle is deleted or xsound gets restarted). Also, I do apologize if these issues are just from _MusicEverywhere_ and not from xsound.

**Comment by Xogy** [comment]
> > It doesn't have to be exactly the issue with xsound, something in "MusicEveryWhere" can cause this problem, but I will try to look into it.. can you describe your movement to get the volume stuck? For example, you get it stuck by first playing youtube, then mp3 and after that, you will play some radio.
> > or would be best to send me the exact same thing you did, all URLs that lead volume get stuck.
> 
> Sorry for the late reply but I seem to, sadly, be unable to replicate the problem consistently (the uncontrollable part) though getting stuck off is very easy to replicate. By playing: http://173.244.215.163:8270/ (GotRadio Top 40 station) and then going to like http://173.244.215.163:8250/ (GotRadio The Mix station) it will not start to play without messing with the volume/play/pause buttons or putting the link in a few times. The getting stuck on only seems to happen randomly with other players on, I'm thinking the get stuck on one might be from _MusicEverywhere_ or just. At any rate, I have reported it to the creator of that addon as well since the more I think about it, it could be either-or (as _MusicEverywhere_ plays on the entity and if it does get glitched, it stops once the vehicle is deleted or xsound gets restarted). Also, I do apologize if these issues are just from _MusicEverywhere_ and not from xsound.

Don't worry, I will test it and we will see if I will be able to replicate the problem.

**Comment by Xogy** [comment]
Alright, I tested the thing and found out nothing really happens.

`xsound = exports.xsound

Citizen.CreateThread(function()
    local pos = GetEntityCoords(PlayerPedId())
    local switch = false
    xsound:PlayUrlPos("Test", "http://173.244.215.163:8270/", 0.5, pos)
    Wait(3000)
    while true do
        Wait(10000)
        if switch then
            xsound:setSoundURL("Test", "http://173.244.215.163:8270/")
            print("new url", switch)
            switch = false
        else
            xsound:setSoundURL("Test", "http://173.244.215.163:8250/")
            print("new url", switch)
            switch = true
        end
    end
end)


Citizen.CreateThread(function()
    local volume = 1
    while true do
        Wait(100)
        volume = volume - 0.05
        if volume < 0 then
            volume = 1
        end
        if xsound:soundExists("Test") then
            xsound:setVolume("Test", volume)
        end
    end
end)`

this was the code I was testing with it. So you should contact the author for it.
