### ISSUE TITLE
Cannot play the same sound url when called again.

### ISSUE THREAD

**Issue by PhotoshopLOL** [Xogy/xsound#12]
**Describe the bug**

- Cannot play the same url again.

**To Reproduce**

- Steps to reproduce the behavior:

```
RegisterCommand('soundtest', function()
    exports['xsound']:PlayUrl('tsunami', './sounds/tsunami.ogg', 0.8)
end, false)
```

- The sound plays when you execute the command the first time, but when executed again after the sound has finished, it throws this error:

![Screenshot_119](https://user-images.githubusercontent.com/7889116/118719619-4723df00-b85b-11eb-8c39-aabebdffd837.png)

the same error gets thrown even when I specified ``false`` to the loop parameter

`exports['xsound']:PlayUrl('tsunami', './sounds/tsunami.ogg', 0.8, false)`

**Expected behavior**

- The sound should be able to play again since by default it gets destroyed on finish.

**Screenshots**

- See above

**Additional context**

- tsunami.ogg is 30 seconds long

**Comment by Xogy** [comment]
Should be fixed in next commit.

**Comment by PhotoshopLOL** [comment]
Good stuff man. This issue is now fixed.
