### ISSUE TITLE
PlayUrl volume setting not working.

### ISSUE THREAD

**Issue by Rubylium** [Xogy/xsound#2]
After doing some test, the volume argument in PlayUrl do not work well.
I did some test setting the value to 0 / 1 / 10 / 50, whatever i do the sound will still be played at max volume. i added a consol.log to check if the value was seded and yes it is, the volume is just ... not changing ^^

**Comment by Xogy** [comment]
are you using right function for it ?

`
setVolume(name,volume) volume is from 0.0 to 1.0
Will set a new value to volume. **Should be used for non 3D sound**

setVolumeMax(name,volume) volume is from 0.0 to 1.0
will set new value to max volume. **Should be used only for 3D sound**
`

also, the volume can be only between 0.0 to 1.0

**Comment by Rubylium** [comment]
![image](https://user-images.githubusercontent.com/19718604/82119280-60dca300-977d-11ea-9f9e-d314f2995dd6.png)
Already tried, not working.
( Btw i'm not using the export, the code is inside my core so not needed )

**Comment by Xogy** [comment]
fixed.

**Comment by Rubylium** [comment]
Working great now ! Thanks for the fix!

**Comment by Xogy** [comment]
np, thanks for reporting.
