### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by bcortezf** [Xogy/xsound#21]
**Describe the bug**
TTS is not working, at least for me.

**To Reproduce**
1. Execute the TextToSpeech function
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/51462063/156623974-9c1a40b5-1d5e-482f-875f-83162d2f855d.png)

![image](https://user-images.githubusercontent.com/51462063/156623738-e3e21f69-98e5-48fd-89e6-d98d66a38677.png)
![image](https://user-images.githubusercontent.com/51462063/156624062-55ef976e-9a32-49fd-a83a-993be76b84bf.png)

**Additional context**
It seems to return 404. The link works well in navigator, but doesnt work when running from FiveM NUI.

Link executed: https://translate.google.com/translate_tts?ie=UTF-8&q=Prueba%20prueba&tl=es-CL&total=1&idx=0&client=tw-ob

Have a nice day.

**Comment by Xogy** [comment]
I removed the TTS function since I wasn't able to fix it to this day, hopefully, I will find some free API that does not require an API key to run and can run more instances at once.
