### ISSUE TITLE
code example in readme

### ISSUE THREAD

**Issue by ElArthuro90** [Xogy/xsound#28]
**Is your feature request related to a problem? Please describe.**
i dont understand how to use this script.

i try:
exports.xsound:PlayUrl("test", "https://www.youtube.com/watch?v=zud9LiIS7IQ&ab_channel=GamerBoy1999999", 1.0)
exports.xsound:PlayUrl("test", "http://xsound/html/sounds/demo", 1.0)
exports.xsound:PlayUrl("test", "https://xsound/html/sounds/demo", 1.0)
exports.xsound:PlayUrl("test", "http://xsound/html/sounds/demo.ogg", 1.0)
exports.xsound:PlayUrl("test", "https://xsound/html/sounds/demo.ogg", 1.0)

(demo.ogg is added in the resource directory)
(no changes in config)
(i try this in RedM -> manifest updated)

but nothing of them play the sound

**Describe the solution you'd like**
a code snipped with an example how to use this script in your readme or would be very helpful.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by daf03** [comment]
i need some examples for server side can you help?

**Comment by Xogy** [comment]
> **Is your feature request related to a problem? Please describe.** i dont understand how to use this script.
> 
> i try: exports.xsound:PlayUrl("test", "https://www.youtube.com/watch?v=zud9LiIS7IQ&ab_channel=GamerBoy1999999", 1.0) exports.xsound:PlayUrl("test", "http://xsound/html/sounds/demo", 1.0) exports.xsound:PlayUrl("test", "https://xsound/html/sounds/demo", 1.0) exports.xsound:PlayUrl("test", "http://xsound/html/sounds/demo.ogg", 1.0) exports.xsound:PlayUrl("test", "https://xsound/html/sounds/demo.ogg", 1.0)
> 
> (demo.ogg is added in the resource directory) (no changes in config) (i try this in RedM -> manifest updated)
> 
> but nothing of them play the sound
> 
> **Describe the solution you'd like** a code snipped with an example how to use this script in your readme or would be very helpful.
> 
> ## **Describe alternatives you've considered**
> ## **Additional context**

that's easy you just need to define path like you would do it in css/html meaning "./path/music.mp3"
