### ISSUE TITLE
sorry, but ain't working

### ISSUE THREAD

**Issue by xrtw** [Xogy/xsound#3]
client.lua:

> xSound = exports.xsound
> 
> local musicId
> local playing = false
> Citizen.CreateThread(function()
>     Citizen.Wait(1000)
>     musicId = "music_id_" .. PlayerPedId()
>     local pos
>     while true do
>         Citizen.Wait(100)
>         if xSound:soundExists(musicId) and playing then
>             if xSound:isPlaying(musicId) then
>                 pos = GetEntityCoords(PlayerPedId())
>                 TriggerServerEvent("myevent:soundStatus", "position", musicId, { position = pos })
>             else
>                 Citizen.Wait(1000)
>             end
>         else
>             Citizen.Wait(1000)
>         end
>     end
> end)
> 
> RegisterCommand("playmusic", function(source, args, rawCommand)
>     local pos = GetEntityCoords(PlayerPedId())
>     local songs = { "https://www.youtube.com/watch?v=Cub8V9DXApI", "https://www.youtube.com/watch?v=6Dh-RL__uN4", "https://www.youtube.com/watch?v=XbGs_qK2PQA","https://www.youtube.com/watch?v=r_0JjYUe5jo"}
>     playing = true
>     TriggerServerEvent("myevent:soundStatus", "play", musicId, { position = pos, link = (songs[math.random(#songs)]) })
> end, false)
> 
> RegisterNetEvent("myevent:soundStatus")
> AddEventHandler("myevent:soundStatus", function(type, musicId, data)
>     if type == "position" then
>         if xSound:soundExists(musicId) then
>             xSound:Position(musicId, data.position)
>         end
>     end
> 
>     if type == "play" then
>         xSound:PlayUrlPos(musicId, data.link, 1, data.position)
>         xSound:Distance(musicId, 20)
>     end
> end)

server.lua

> RegisterNetEvent("myevent:soundStatus")
> AddEventHandler("myevent:soundStatus", function(type, musicId, data)
>     TriggerClientEvent("myevent:soundStatus", -1, type, musicId, data)
> end)

fxmanifest.lua

> fx_version 'adamant'
> game 'gta5'
> 
> server_scripts {
> 	'server/main.lua',
> }
> 
> client_scripts {
> 	'client/*.lua',
> }

**Comment by Xogy** [comment]
Wrong fxmanifest.lua

change
game 'gta5'
to
games { 'gta5' }
