### ISSUE TITLE
Script should care about walls and borders

### ISSUE THREAD

**Issue by KlosteinRaucher** [Xogy/xsound#30]
Hello, 
for the future i wish,
that the script cares about walls within the musicrange, so that the played music sounds dull.

I hope its makeable.

**Comment by Xogy** [comment]
> Hello, for the future i wish, that the script cares about walls within the musicrange, so that the played music sounds dull.
> 
> I hope its makeable.

Sadly it ain't makeable with youtube API since I cannot force any sound effects to youtube API without converting the music to mp3/ogg/any other music file. And that would go against youtube TOS which  I am not fan of.
