### ISSUE TITLE
Error when using with Red M

### ISSUE THREAD

**Issue by DerHobbs** [Xogy/xsound#31]
**Describe the bug**

**To Reproduce**
1. As soon as the interlocutor picks up the phone, these errors come

**Expected behavior**

**Screenshots**

![Screenshot_8](https://user-images.githubusercontent.com/101003021/188672528-757aabef-78d2-431b-9431-a9040a143417.png)
![Fh6xxbaDRymxFzq8JTEqDA](https://user-images.githubusercontent.com/101003021/188672647-96213f37-a0b3-476c-bb2f-f2f3c9a5df1b.png)

https://streamable.com/3pc56o

**Additional context**
The script creator says it's up to xsound, which is why I wanted to ask you if you have any idea what the problem is.

Warm greetings

**Comment by Xogy** [comment]
Sadly I don't have RedM so I don't know if the chromium there works slightly differently, I can't test it out so if you know how to fix it feel free to make a fork.
