### ISSUE TITLE
Lagging music at fast speeds

### ISSUE THREAD

**Issue by Lexigal1984** [Xogy/xsound#32]
I am having an issue in my server. The Phone we're using is GKS Phone. Once you get over 100 mph the phone music starts to lag and cut out. It only gets worse the faster you go. I reported it to them (GKS Phone), they stated it is an issue with xsound on the coords updating. Would I need to update the refresh rate in config or what steps should I take on fixing this?

**Comment by Xogy** [comment]
Either by updating the distance of the sound or decreasing the refresh rate.
