### ISSUE TITLE
Sounds are playing late

### ISSUE THREAD

**Issue by LySoon** [Xogy/xsound#33]
i wanted to use xsound for pop up exhaust sounds for my script, but sounds are running late and can't be stacked up

**Comment by Xogy** [comment]
I will fix the late sound but the stacking is your issue of the way you're handling code. Dont use same identifier for the sound.

**Comment by LySoon** [comment]
Okay, for stacking i can assign different ids to each sound its fine ^^

Also thanks for caring, the 3D sounds would godly for pop up sound ^^
