### ISSUE TITLE
seekTo() is not an function

### ISSUE THREAD

**Issue by mir1mikeeee** [Xogy/xsound#38]
hey,

we have an uncaught error with this.yPlayer.seekTo(time) is not an function.
can you fix that? 

![image](https://user-images.githubusercontent.com/16014232/204097709-99316fe8-5285-47ea-9aa3-fbb1be066c1d.png)

**Comment by Xogy** [comment]
![image](https://user-images.githubusercontent.com/49158267/204105481-441ffe61-6c54-42a5-966b-c4b975e2dd69.png)
Please update your xsound.
