### ISSUE TITLE
Youtube sound URLs no longer play on 1.4.2

### ISSUE THREAD

**Issue by davidxd33** [Xogy/xsound#39]
**Describe the bug**
On 1.4.1 and below, I've been using the server exports to play sounds from direct URLs on youtube. After updating to 1.4.2 to get the memory leak fixes, I can no longer play URLs.

**To Reproduce**

```lua
RegisterCommand('test', function(source)
    exports['xsound']:PlayUrl(source, 'test', 'https://www.youtube.com/watch?v=_4kHxtiuML0', 0.02, true)
end)
```

**Expected behavior**
The sound should play on the source client. On 1.4.1, the sound plays, on 1.4.2, it does not.

**Comment by Xogy** [comment]
Should be fixed in newest release please try it @davidxd33
