### ISSUE TITLE
Max Duration and Timestamp always return 0

### ISSUE THREAD

**Issue by AdlanDzulkfali** [Xogy/xsound#40]
When I try to get the sound info. maxduration and timestamp always return 0 for youtube song. Is this expected or is it a bug? below is the data that I've captured

{"maxDuration":0,"volume":0.55,"timeStamp":0,"paused":false,"isDynamic":true,"loop":false,"distance":10,"url":"https://www.youtube.com/watch?v=nKgN0ZzJP4c","playing":true,"position":{"x":82.59248352050781,"y":-865.4900512695313,"z":134.7701416015625},"id":"test","destroyOnFinish":true}

**Comment by Xogy** [comment]
> When I try to get the sound info. maxduration and timestamp always return 0 for youtube song. Is this expected or is it a bug? below is the data that I've captured
> 
> {"maxDuration":0,"volume":0.55,"timeStamp":0,"paused":false,"isDynamic":true,"loop":false,"distance":10,"url":"[https://www.youtube.com/watch?v=nKgN0ZzJP4c","playing":true,"position":{"x":82.59248352050781,"y":-865.4900512695313,"z":134.7701416015625},"id":"test","destroyOnFinish":true}](https://www.youtube.com/watch?v=nKgN0ZzJP4c%22,%22playing%22:true,%22position%22:%7B%22x%22:82.59248352050781,%22y%22:-865.4900512695313,%22z%22:134.7701416015625%7D,%22id%22:%22test%22,%22destroyOnFinish%22:true%7D)

The onPlay event has priority over timestamp you have to just wait 1ms to get the timestamp aswell. I will switch the priority event so it can be done without waiting.

```LUA
CreateThread(function()
    Wait(2000)

    PlayUrlPos("test", "https://www.youtube.com/watch?v=nKgN0ZzJP4c", 0.55, GetEntityCoords(PlayerPedId()), false)

    onPlayStart("test", function()
        Wait(1)
        dump(getInfo("test"))
    end)
end)
```

**Comment by Xogy** [comment]
https://github.com/Xogy/xsound/commit/cd313f920a841241c030b0171c59400f9bac3c40
