### ISSUE TITLE
After TriggerServerEvent to execute xSound:PlayUrlPos() , trying to client side xSound:IsPlaying(id) gives error

### ISSUE THREAD

**Issue by fferrandini** [Xogy/xsound#42]
**Describe the bug**

I'm trying to create a playlist using xsound, i have a list of songs and this function for testing it in client-side: 

`
function playPlaylist(coords, id)
    local musics = {
        'https://www.youtube.com/watch?v=9ug1xj2-yBo',
        'https://www.youtube.com/watch?v=iOM20kM2gOQ'
    }
    if #musics > 0 then
        TriggerServerEvent("chucky_bailefunk:play_music", id, musics[1], 1, coords)
        
        if xSound:isPlaying(id) then
            print('is playing music')
        end
    end
end
`

the songs plays after server-side is triggered. what i want to do is to check if there is a sound being played.

`if xSound:isPlaying(id) then`

after that i want to check sound getMaxDuration, so i will set a Wait(xSound:getMaxDuration(id)) in the for-loop that goes through "musics".

but i'm getting : 

An error occurred while calling export `isPlaying` in resource `xsound`:
___

**Expected behavior**
`
if xSound:isPlaying(id) then
    local max_duration = xSound:getMaxDuration(id)
    Wait(max_duration)
    Loop throug "musics"
end
`

**Comment by Xogy** [comment]
Hey please pack the resource in zip so I can reproduce it on my local server.

**Comment by fferrandini** [comment]
sorry man...

i was using it wrong... some functions are only client-side .. that needed
to play sound on client side.. i use server side to all players.

Em ter., 7 de fev. de 2023 às 10:25, MrXogos ***@***.***>
escreveu:
