### ISSUE TITLE
getSharedObject

### ISSUE THREAD

**Issue by svenbledt** [Xogy/xsound#44]
**Describe the bug**
The Bug is normal with old Ressources it tells that xsound is using old getSharedObject from ESX
The new ESX definition is exports['es_extended']:getSharedObject()

Should be quickly fixxed but i couldn't find it in your resource. 

Thanks ;)

**To Reproduce**
1. Start the resource with esx version 1.9.1
2. See error

**Expected behavior**
No error

**Comment by Xogy** [comment]
https://github.com/Xogy/xsound/commit/8d7411e5bc5df08e7ce03c3082a48df2558c94b2
