### ISSUE TITLE
Warning: could not find file `html/sounds/*.ogg` (defined in fxmanifest.lua:35)

### ISSUE THREAD

**Issue by FrogCF** [Xogy/xsound#47]
**Warning: could not find file `html/sounds/*.ogg` (defined in fxmanifest.lua:35)**

Hi,
Despite the fact that we are using the most recent version of QB-Core, we have observed an error in our console that reads: ( **Warning: could not find file `html/sounds/*.ogg` (defined in fxmanifest.lua:35**)

**To Reproduce**
reproduce this mistake the issue is displayed in the FX console after downloading the most recent version of QB-core.

**Expected behavior**
No error prints or messages

**Screenshots**
![Screenshot 2023-06-01 190016](https://github.com/Xogy/xsound/assets/39281740/019ffc72-58e7-41bd-bb5b-289aafe9c5b1)

**Comment by FrogCF** [comment]
fxmanifest reads now!!

fx_version 'cerulean'
games { 'gta5', 'rdr3' }

rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'

client_scripts {
	"config.lua",
	"client/main.lua",
	"client/events.lua",
	"client/commands.lua",

	"client/exports/info.lua",
	"client/exports/play.lua",
	"client/exports/manipulation.lua",
	"client/exports/events.lua",
	"client/effects/main.lua",

	"client/emulator/interact_sound/client.lua",

	"addon/**/client/*.lua",
}

server_scripts {
	"config.lua",
	"server/exports/play.lua",
	"server/exports/manipulation.lua",

	"server/emulator/interact_sound/server.lua",

	"addon/**/server/*.lua",
}

ui_page "html/index.html"

files {
	"html/index.html",

	"html/scripts/listener.js",
	"html/scripts/SoundPlayer.js",
	"html/scripts/functions.js",

	--"html/sounds/*.ogg", # IF THESE FILES ARE MISSING DO WE REALLY NEED THEM
	--"html/sounds/*.mp3", # IF THESEE FILES ARE MISSING DO WE REALLY NEED THEM
}

**Comment by Xogy** [comment]
https://github.com/Xogy/xsound/issues/46
