### ISSUE TITLE
High tick problem, bad optimized on client side.

### ISSUE THREAD

**Issue by Tinky124** [Xogy/xsound#5]
![6666](https://user-images.githubusercontent.com/48660658/98135653-5dbaa800-1ec0-11eb-904c-0e4bd5d42092.png)
![5335](https://user-images.githubusercontent.com/48660658/98135660-5f846b80-1ec0-11eb-9140-4fdc339e050d.png)

**Comment by Xogy** [comment]
I will try it optimized it but I don't think I will go any further. there is just one function that takes too much tick and it's "SendNuiMessage" the only thing I can do is check if the player is near close to sound and start updating the sound... but I don't think it will get any better.

**Comment by Xogy** [comment]
I pushed an update that could fix the high tick.

**Comment by Tinky124** [comment]
@Xogy ty, it fixed its better to use check if player is near clote to sound and start updating sound.

**Comment by Xogy** [comment]
welp, I didn't want that cuz for example you can be in a car and driving around and just hear it for simple 3 seconds is a cool effect.. this kill the cool effect.. :D but it can be fixed if you just change the value in "config.distanceBeforeUpdatingPos = 40" to something like 150.
