### ISSUE TITLE
seekTo() is not an function

### ISSUE THREAD

**Issue by TonyWilly** [Xogy/xsound#52]
**Describe the bug**
While using setTimeStamp for any time amount I get:
"[   2729922] [b2802_GTAProce]        CrBrowserMain/ Uncaught TypeError: this.yPlayer.seekTo is not a function (@xsound/html/scripts/SoundPlayer.js:320)"
and also
"[   2730032] [b2802_GTAProce]        CrBrowserMain/ Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'. (:0)" when I open log file.

**To Reproduce**
xsound = exports.xsound
xsound:PlayUrl("localCar", url, 0.3, true)
xsound:setTimeStamp("localCar", 30)

**Expected behavior**
Seek to timestamp after playing

**Screenshots**
![image](https://github.com/Xogy/xsound/assets/98055567/ff5dbeea-8762-49e3-a798-58a84d1e3059)

**Additional context**
I saw the #38 issue and I have ensured that I am using xsound-1.4.3
I also tried to research on the YouTube iframe and found this:
player.seekTo(seconds:Number, allowSeekAhead:Boolean):Void
So I tried to edit SoundPlayer.js to be:
            this.yPlayer.seekTo(time, true);
but that didn't change the error.

**Comment by TonyWilly** [comment]
After testing, it seems this is just an issue of the player not being loaded before the set duration is called right way. Currently trying to figure out a good way to wait until the player has fully loaded...

**Comment by Xogy** [comment]
> After testing, it seems this is just an issue of the player not being loaded before the set duration is called right way. Currently trying to figure out a good way to wait until the player has fully loaded...

Hey simply use event

`
onPlayStart("localCar", function()
     setTimeStamp("localCar", 30)
end)
`
