### ISSUE TITLE
Error at Initialization 

### ISSUE THREAD

**Issue by ALFAMAS** [Xogy/xsound#53]
**Describe the bug**
when i initialize the script it throws an error in the Javascript

**To Reproduce**
1. Go to '/xsound/html/scripts'
2. Click on 'SoundPlayer.js'
3. Scroll down to 'Line - 320'

``` Uncaught TypeError: this.yPlayer.seekTo is not a function (@xsound/html/scripts/SoundPlayer.js:320) ```

``` Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'. (:0) ```

**Comment by Xogy** [comment]
This is an issue of how the function "setTimeStamp" is handled it has to be called from "onPlayStart"
