### ISSUE TITLE
Export onPlayEnd is not working

### ISSUE THREAD

**Issue by Red-Killer** [Xogy/xsound#54]
**Describe the bug**
The export onPlayEnd is not working im getting this error below:
```
802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @xsound/client/exports/events.lua:8: attempt to index a nil value (field '?')^7
[   9195937] [b2802_GTAProce]             MainThrd/ ^3> ref^7 (^5@xsound/client/exports/events.lua^7:8)
[   9195937] [b2802_GTAProce]             MainThrd/ ^3> fn^7 (^5@lb-musicapp/client.lua^7:112)
[   9195937] [b2802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @lb-musicapp/client.lua:112: 
[   9195937] [b2802_GTAProce]             MainThrd/ ^5 An error occurred while calling export `onPlayEnd` in resource `xsound`:
```

![image](https://github.com/Xogy/xsound/assets/59504268/e76f8aa1-0a08-4045-8f36-146127594359)

My Code:
```
xSound:onPlayEnd(musicId, function()
    print("end")
end)
```

![image](https://github.com/Xogy/xsound/assets/59504268/08e85ae8-0588-410e-b656-72f7415695dd)

**Comment by Xogy** [comment]
This is expected if the sound ID doesnt exists you cannot use these events they have to be called after PlayUrl / PlayUrlPos

![image](https://github.com/Xogy/xsound/assets/49158267/4aba9e97-c7bf-4824-bf1e-a01ff8750301)
![image](https://github.com/Xogy/xsound/assets/49158267/fdfc8deb-972e-4370-8275-e1dc27b2b4ad)

**Comment by Red-Killer** [comment]
Oh okay
