### ISSUE TITLE
For some reason, distance isn't working

### ISSUE THREAD

**Issue by bosskitz** [Xogy/xsound#55]
Here is the code I am using: Client side.

> RegisterNetEvent("resource-name:eventname")
> AddEventHandler("resource-name:eventname", function(audioUrl, volume, distance, rand)
> 	local playerped = PlayerPedId()
> 	local pedcoords = GetEntityCoords(playerped)
> 	local rand = rand
> 	exports['xsound']:PlayUrlPos('resp'..rand, audioUrl, volume, pedcoords)
> 	exports['xsound']:Distance('resp'..rand, distance)
> 	exports['xsound']:setSoundDynamic('resp'..rand, true)
> 	print(json.encode(exports['xsound']:getInfo('resp'..rand)))
> 	--exports['xsound']:Destroy('resp'..rand, true)
> end)

Current status: Basically, the audio is working. We're able to hear it. I am using Google tts API for this and it works perfectly fine.
Problem is, I am not sure if I'm implementing distance properly.
![image](https://github.com/Xogy/xsound/assets/52140422/68e79cf1-966d-435e-936e-ce1b99624646)
But it shows here (image) that the distance is set and coords is also set. Did some print tests too and these are set properly.

Problem is, it is still being heard by everyone.
Kindly advise, thank you.

**Comment by Xogy** [comment]
"Problem is, it is still being heard by everyone. Kindly advise, thank you."

Are you using an old version? This issue is known in older versions.

**Comment by bosskitz** [comment]
Thanks for your response.
I am actually using the latest release.
> --[[ Resource Information ]]--
> name         'xsound'
> version      '1.4.3'

And fortunately, I have found the issue.
The thing is, coords and distance and all parameters do work.
It was confusing at first because we were all hearing it but then noticed that when someone triggers the event, it is being triggered to all PlayersIds instead of only the source.
I'm using the client side events only cuz for some reason, server side exports never really worked for me.

Thanks for your response.

**Comment by Xogy** [comment]
You will still need to trigger for every client on your server but send the initial source coordination
