### ISSUE TITLE
Begin is cut off

### ISSUE THREAD

**Issue by Madbull16** [Xogy/xsound#58]
When using the PlayUrlPosition export on client side most of the time the first moments of the soundfiles are not played.

"exports['xsound']:PlayUrlPos('gekauft', "./sounds/gekauft_m_01.mp3", 1, vector3(1163.4504, -323.2734, 69.2051))"
Video of bug: www.sabanto.de/xsound_issue.mp4
Sourcefile: www.sabanto.de/gekauft_m_01.mp3

**Comment by Xogy** [comment]
Make sure you have newest xsound on your server I cannot replicate it at all

https://github.com/Xogy/xsound/assets/49158267/d171f9fd-41c5-4c7e-b411-cc2857b615d0
