### ISSUE TITLE
Set Looping Option

### ISSUE THREAD

**Issue by inQonsole** [Xogy/xsound#6]
The library is working very well,

A nice feature would be to have an option SetLooping(true/false) so instead of using Destroy and the sounds stops right away, SetLooping will finish playing the audio file and then stop, then you can check with IsLooping() if the sound has finished and Destroy it.

Great job and thanks for the amazing work.

**Comment by Xogy** [comment]
true, I forgot about "SetLoop" thanks for the reminder. I will add this option later.

Also, I don't think it is really a wise decision to delete the sound after finished playing(not with the IsLooping() fce) I want to add this feature list

1. SetLoop(identifier, bool)
2. Repeat(identifier)
3. ChangeURL(identifier, string)
4. DestroyOnFinish(identifier)

**Comment by inQonsole** [comment]
Thank you so much!

Yes, that will be great features, will make it usable in so many ways, 

Yeah if you can stop the loop and resume it when needed there is no need to destroy it if it's still needed.

The library works amazing, also the resources used are very low, awesome job, looking forward to the added features.

**Comment by Xogy** [comment]
Added in newest commit
