### ISSUE TITLE
Playing a sound twice is not working

### ISSUE THREAD

**Issue by manzarek123** [Xogy/xsound#7]
Not sure what I am doing wrong but if I call twice:
xSound:PlayUrlPos('car_lock', './sounds/car_lock.ogg', 1, GetEntityCoords(vehicle))
xSound:Distance('car_lock', 10)

I only hear it the first time and I must restart the resource for it to work again of change the sound name

**Comment by manzarek123** [comment]
It is working fine on 1.2.3

**Comment by Xogy** [comment]
I recommend getting the 1.2.5 version

and if you want to have more sounds in the same position the identifier cant be the same as the previous one, so the identifier will look like something like this "car_lock_1", "car_lock_2" etc

**Comment by Xogy** [comment]
Fixed in the newest commit, thanks for the report :)
