### ISSUE TITLE
youtube errors

### ISSUE THREAD

**Issue by Jokiblack** [Xogy/xsound#9]
in many youtube songs before it did not happen
![image](https://user-images.githubusercontent.com/8556969/107131730-58169900-68d9-11eb-8f7b-483f03a85efb.png)

**Comment by Xogy** [comment]
Well, the picture doesn't say much neither do you. How am I supposed to solve this problem with this little information?

**Comment by Jokiblack** [comment]
It seems that the song is going to start playing and it does not sound, or it starts playing after 15 seconds or a minute

**Comment by Xogy** [comment]
Please contact me on Xogos#6422
